name: Flutter Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.x' # 프로젝트에 맞는 버전 설정

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Tests
      run: flutter test --coverage

    - name: Generate Coverage Report Image
      run:  lcov-to-image-script coverage/lcov.info

    - name: Upload Coverage Report Image
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report-image
        path: path/to/coverage-report
    # 이미지를 Pull Request에 표시
    - name: Post Coverage Image to PR
      uses: unsplash/comment-on-pr@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: '![Coverage Report](path/to/coverage-report-image.png)'
        check_for_duplicate_msg: false
