name: Flutter Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.x' # 사용하는 Flutter 버전에 맞게 설정

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Tests
      run: flutter test --coverage

    - name: Generate HTML Report from lcov
      run: |
        sudo apt-get update
        sudo apt-get install lcov
        lcov --remove coverage/lcov.info 'lib/**.g.dart' -o coverage/lcov.info # 필요에 따라 제외할 파일 설정
        genhtml coverage/lcov.info --output=coverage/

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage/

    # 추가 단계: 커버리지 요약을 Pull Request에 코멘트로 게시
    - name: Post Coverage Comment to PR
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        lcov_file: ./coverage/lcov.info
     
